
artist_data = [["Pop", "Harry Styles", "1", "As It Was", "3"],
                ["Rap", "Post Malone", "2", "Circles", "4"],
                ["Latin", "Bad Bunny", "3", "Me Porto Bonito", "5"],
                ["Country", "Morgan Wallen", "4", "You Proof", "2"],
                ["K-Pop", "SEVENTEEN", "5", "Oh My!", "4"],
                ["Pop", "Doja Cat", "6", "Woman", "3"],
                ["Rap", "Kendrick Lamar", "7", "Alright", "5"],
                ["Pop", "Ed Sheeran", "8", "The A Team", "5"],
                ["Rap", "Jack Harlow", "9", "First Class", "2"],
                ["R&B", "The Weeknd", "10", "The Hills", "5"],
                ["Rap", "Future", "11", "WAIT FOR U", "9"],
                ["Pop", "Olivia Rodrigo", "12", "good 4 u", "1"],
                ["Rap", "Drake", "13", "ONE DANCE", "7"],
                ["Country", "Luke Combs", "14", "Forever After All", "2"],
                ["Rap", "Lil Baby", "15", "Woah", "2"],
                ["Pop", "Kate Bush", "16", "The Man with the Child in His Eyes", "10"],
                ["R&B", "Prince", "17", "Purple Rain", "42"],
                ["Pop", "Dua Lipa", "18", "Don't Start Now", "2"],
                ["R&B", "Lizzo", "19", "About Damn Time", "3"],
                ["Hip-Hop", "Kanye West", "20", "stronger", "11"],
                ["Pop", "Justin Bieber", "21", "STAY", "6"],
                ["Country", "Chris Stapleton", "22", "Tennessee Whiskey", "4"],
                ["Country", "Taylor Swift", "23", "Shake it Off", "9"],
                ["R&B", "Bruno Mars", "24", "Uptown Funk", "3"],
                ["Alternative", "Imagine Dragons", "25", "Enemy", "5"],
                ["Hip-Hop", "Latto", "26", "Big Energy", "2"],
                ["Country", "Walker Hayes", "27", "You Broke Up With Me", "3"],
                ["Rap", "Lil Nas X", "28", "THATS WHAT I WANT", "1"],
                ["Pop", "Lady Gaga", "29", "Hold My Hand", "5"],
                ["Rap", "The Kid LAROI", "30", "STAY", "1"],
                ["Rock", "Fleetwood Mac", "31", "Go Your Own Way", "18"],
                ["Country", "Jason Aldean", "32", "Dirt Road Anthem", "10"],
                ["K-Pop", "TOMORROW X TOGETHER", "33", "PS5", "3"],
                ["Rock", "Glass Animals", "34", "Heat Waves", "3"],
                ["Alternative", "Billy Eilish", "35", "bury a friend", "2"],
                ["Pop", "Adele", "36", "Rolling in the Deep", "4"],
                ["Hip-Hop", "Eminem", "37", "Lose Yourself", "11"],
                ["Hip-Hop", "Tyler, the Creator", "38", "See You Again", "6"],
                ["Rap", "Kodak Black", "39", "Silent Hill", "4"],
                ["Rock", "The Beatles", "40", "A Day in the Life", "21"],
                ["R&B", "SZA", "41", "Love Galore", "1"],
                ["Rock", "Def Leopard", "42", "Bringin' on the Heartbreak", "12"],
                ["Rock", "Metallica", "43", "one", "10"],
                ["Rock", "Queen", "44", "Bohemian Rhapsody", "15"],
                ["Country", "Kane Brown", "45", "Be Like That", "2"],
                ["Hip-Hop", "Polo G", "46", "Better Days", "3"],
                ["Country", "Miranda Lambert", "47", "Drunk (And I Don't Wanna Go Home)", "10"],
                ["Hip-Hop", "Childish Gambino", "48", "Redbone (2016)", "4"],
                ["Hip-Hop", "J. Cole", "49", "Lights Please", "6"],
                ["K-Pop", "BTS", "50", "Butter", "9"]]
